apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeClaimPolicy: Recycle
  nfs:
    path: /
    server: 10.255.255.10
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-test-claim
  namespace: test
  labels:
    tier: test
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: mysql