apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-access-production
  namespace: production
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {node1, node2, node3}
    - nodeSelector:
        kubernetes.io/hostname: 
        - node1
        - node2
        - node3
  egress:
  - to:
    - podSelector: {}

