apiVersion: v1
kind: Role
metadata:
  name: junior
  namespace: test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["read", "list", "create"]
---
apiVersion: v1
kind: Role
metadata:
  name: junior
  namespace: production
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["read", "list"]
---
apiVersion: v1
kind: Role
metadata:
  name: senior
  namespace: test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["read", "list", "create"]
---
apiVersion: v1
kind: Role
metadata:
  name: senior
  namespace: production
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["read", "list", "create"]