apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: junior
  namespace: test
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["edit"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: junior
  namespace: production
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["read", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: senior
  namespace: test
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["edit"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: senior
  namespace: production
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["edit"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: senior
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["view"]